# Islandora Dev Settings to be used with $app['debug'] == TRUE
islandora:
  fedoraProtocol: http
  fedoraHost: "localhost:8080"
  fedoraPath: /rest
  tripleProtocol: http
  tripleHost: "localhost:9999"
  triplePath: /bigdata/sparql
  resourceIdRegex: "(?:[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})?"